apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: edge-service-svc
  labels:
    app: edge-service
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30082
  selector:
    app: edge-service
kind: Deployment
metadata:
  name: edge-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
      - name: edge-service
        image: edge-service:latest
        ports:
        - containerPort: 8081
