apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: eureka-service-svc
  labels:
    app: eureka-service
spec:
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30080
  selector:
    app: eureka-service
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: eureka-service:latest
        ports:
        - containerPort: 8761
